# Generated by Django 5.2.4 on 2025-07-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=15)),
                ("correo", models.EmailField(max_length=254)),
                ("motivo", models.TextField()),
            ],
        ),
    ]
